=== IanMadlenya/SOCR-Java/src/JSci/chemistry/periodictable/elements.dtd
<!-- entities -->

<!ENTITY % series-values "alkali-metal|alkali-earth-metal|halogen|noble-gas|non-metal|metal|rare-earth-metal|transition-metal">
<!ENTITY % potentials "first,second?,third?,fourth?">

<!-- the top level element -->

<!ELEMENT element (name,symbol,atomic-number,mass-number)>
<!ATTLIST element series (%series-values;) #REQUIRED>

<!-- elements -->

<!ELEMENT name                      (#PCDATA)>
<!ELEMENT symbol                    (#PCDATA)>
<!ELEMENT atomic-number             (#PCDATA)>
<!ELEMENT mass-number               (#PCDATA)>
<!ELEMENT electronegativity         (#PCDATA)>
<!ELEMENT ionization-potentials     (%potentials;)>
   <!ELEMENT first    (#PCDATA)>
   <!ELEMENT second   (#PCDATA)>
   <!ELEMENT third    (#PCDATA)>
   <!ELEMENT fourth   (#PCDATA)>
<!ELEMENT covalent-radius           (#PCDATA)>
<!ELEMENT atomic-radius             (#PCDATA)>
<!ELEMENT melting-point             (#PCDATA)>
<!ELEMENT boiling-point             (#PCDATA)>
<!ELEMENT density                   (#PCDATA)>
<!ELEMENT specific-heat             (#PCDATA)>
<!ELEMENT electrical-conductivity   (#PCDATA)>
<!ELEMENT thermal-conductivity      (#PCDATA)>

=== IanMadlenya/SOCR-Java/src/JSci/chemistry/periodictable/calcium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="alkali-earth-metal">
   <name>Calcium</name>
   <symbol>Ca</symbol>
   <atomic-number>20</atomic-number>
   <mass-number>40</mass-number>
   <electronegativity>1.00</electronegativity>
   <covalent-radius>1.74</covalent-radius>
   <atomic-radius>2.23</atomic-radius>
   <melting-point>1112.0</melting-point>
   <boiling-point>1757.0</boiling-point>
   <density>1.55</density>
   <specific-heat>0.63</specific-heat>
   <electrical-conductivity>0.298e6</electrical-conductivity>
   <thermal-conductivity>2.0</thermal-conductivity>
</element>

=== IanMadlenya/SOCR-Java/src/JSci/chemistry/periodictable/oxygen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE element SYSTEM "elements.dtd">
<element series="non-metal">
   <name>Oxygen</name>
   <symbol>O</symbol>
   <atomic-number>8</atomic-number>
   <mass-number>16</mass-number>
   <electronegativity>3.44</electronegativity>
   <covalent-radius>0.66</covalent-radius>
   <atomic-radius>0.65</atomic-radius>
   <melting-point>50.35</melting-point>
   <boiling-point>90.13</boiling-point>
   <density>0.001429</density>
   <specific-heat>0.92</specific-heat>
   <electrical-conductivity>0.0</electrical-conductivity>
   <thermal-conductivity>0.0002674</thermal-conductivity>
</element>
